# Assignments {#sec-assignments}

Partner work allowed: yes, maximum groups of three-four (depending on the topic).

Create a text document of 3-5 pages (A4, 11 pt) that answers the content points of your chosen assignment, see links below. You may structure the document along the given questions or as you like. Make sure that references in your text are correctly cited and that each statement is referenced. Ideally, your responses are complemented by a figure from original sources for each point. The document may be handed in as a Word, [RMarkdown](https://geco-bern.github.io/agds/gettingstarted.html#rmarkdown), or [Quarto](https://quarto.org/) document that can be added to the repository of the LES textbook (https://geco-bern.github.io/les/).

The text documents are due to be handed in one week prior to the presentation of the respective topic. A "zero-order draft" is to be handed in on 14.10.2024. See @sec-plan. It should contain an outline of the contents that you are planning to cover in the document (e.g., types of visualisations, etc.)

Present this work in a presentation of 30 min.

## Land use change

- Students: Robbert Kouwehoven, Samuel Müller, Raphael Müller
- Supervision: Benjamin Stocker
- [Assignment Link](https://github.com/geco-bern/les2_course/blob/main/data/les2_assignment_landusechange.pdf)
- [Chapter Link](https://geco-bern.github.io/les/landusechange.html)

## Nitrogen Cycle and Interactions with the Carbon Cycle

- Students: Julian Richter, Martin Sigrist, Livio Conzett
- Supervision: Fabrice Lacroix
- [Assignment Link](https://github.com/geco-bern/les2_course/blob/main/data/les2_assignment_nitrogencycle.pdf)
- [Chapter Link](https://geco-bern.github.io/les/nutrients.html)
- [Recap Lecture Link](https://github.com/geco-bern/les2_course/blob/main/data/les2_recap_nitrogencycle.pdf)

## Terrestrial Greenhouse-Gases

- Students: Shiyuan Feng, Ting Tan, Thomas Rigny
- Supervision: Benjamin Stocker
- [Assignment Link](https://github.com/geco-bern/les2_course/blob/main/data/les2_assignment_ghg.pdf)
- [Chapter Link](https://geco-bern.github.io/les/ghg.html)
- [Recap Lecture Link](https://github.com/geco-bern/les2_course/blob/main/data/les2_recap_les2_recap_ghg.pdf)

## Global environmental change

### Land surface greening

- Students: Florence Hammer, Joris Amiet, Meret Weh
- Supervision: Laura Marqués
- [Assignment Link](https://github.com/geco-bern/les2_course/blob/main/data/les2_assignment_greening.pdf)

### CO~2~ fertilization

- Students: Nils Tinner, Patricia Gribi, Patricia Helpap, Michael Weatherford
- Supervision: Laura Marqués
- [Assignment Link](https://github.com/geco-bern/les2_course/blob/main/data/les2_assignment_co2fert.pdf)
- [Chapter Link](https://geco-bern.github.io/les/globenvchange.html#co2-fertilization)
- [Recap Lecture Link](https://github.com/geco-bern/les2_course/blob/main/data/les2_recap_co2fertilization.pdf)

### Phenology changes

- Students: Lucas Gsponer, Fabio Jakob, Abdelsamed Rasheed
- Supervision: Laura Marqués
- [Assignment Link](https://github.com/geco-bern/les2_course/blob/main/data/les2_assignment_phenology.pdf)
- [Chapter Link](https://geco-bern.github.io/les/globenvchange.html#phenology-changes)
- [Recap Lecture Link](https://github.com/geco-bern/les2_course/blob/main/data/les2_recap_phenology.pdf)
